name: Generate README

on:
  push:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          curates:
            - 'lib/ruby/**'
            - 'lib/js/**'
          templates:
            - 'lib/templates/**'
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.0
        bundler-cache: true
    - name: Install Dependencies
      if: steps.filter.outputs.curates == 'true' || steps.filter.outputs.templates == 'true'
      run: bundle install
    - name: Render README
      if: steps.filter.outputs.curates == 'true' || steps.filter.outputs.templates == 'true'
      run: bundle exec rake render
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update README.md
        commit_options: --signoff
        commit_user_name: GitHub Actions
        file_pattern: README.md
        branch: main
